#basic
use_wandb: False
data_dir: './data/'
log_dir: './log/'
config_dir: './config/'
store_name: 'testrun'
dataset: 'Aminer-G'
use_a_attribute: True
restore: False
use_sample: False
data_size: 1


#train and test
train_author: True
train_group: True
neg_for_test: 100
attr_dim: 2
batch: 256
optimizer: 'AdamW'
scheduler: 'plateau'
gpu: '0'
epoch: 20
eval_step: 1
l2: 0.0
lr: 0.001
num_workers: 8
only_test: False

#graph encoder
only_attribute: False
only_GE: False
graph_based: 'GraphSage'
gcn_layer: 4
init_dim: 128
gcn_dim: 128
embed_dim: 128
dropout: 0.1
att_head: 1

#MMAN
view_num: 3
i2g_method: 'MMAN'

# predict layer
score_method: 'mv_score'
predict_layer: 3
